env:env
eureka:
  client:
    service-url:
      defaultZone: http://localhost1:8761/eureka/
spring:
  application:
    name: order
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://127.0.0.1:3306/product?serverTimezone=Hongkong
